---
title: "行動力"
---

<link rel="stylesheet" href="./style.css">
<script src="smooth_scroll.js"></script>

<script type="text/javascript">
    $(window).on('load',function(){
        $('#exampleModalLong').modal('show');
    });
</script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	dev='svg',
	fig.dim = c(5.5, 3.5)  # (width, height)
)
source("bootstrap_fc.R")
```


## Section 1

[Link To 第三段 MD](#sec3){.btn .btn-success role="button"}


<br>

```{r}
# Button trigger modal
button_bs("Launch", data_toggle="modal", data_target="#first_modal")

modal_body <- button_bs("Take Test", class = "warning", data_toggle = "modal", data_target = "#psytest")

modal_body2 <- button_bs("Proceed", class = "success pull-right", data_dismiss = "modal")

# Modal
modal(modal_header="Header", id="first_modal", modal_body = modal_body, modal_body2 = modal_body2, size = "modal-sm")

iframe <- HTML('<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe8BV2rqj-4n3sKyAkgmO0b01Rzp0mSr2JYHFj_rMfZQARFyw/viewform?embedded=true"  style="position: relative; height: 400px; width: 100%;" frameborder="0" marginheight="0" marginwidth="0">載入中…</iframe>')

modal(id="psytest", modal_header = "行動力量表", modal_body=iframe)
```


<br>

```{r}
button_bs("Launch widget", data_toggle="modal", data_target="#htmlwidget")
```

<br>

<div id="htmlwidget" class="modal fade" role="dialog" tabindex="-1">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">行動力量表</h4>
</div>
<div class="modal-body">

<div class="tab-content">
```{r}
library(heatmaply)
source("./rscript/corr_matrix.R", encoding = "utf-8")
hm
```
</div>

<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
</div>
</div>
</div>
</div>


<br><br><br><br><br><br><br>

## 中文{#chi .tabset}

<div class="alert alert-success" role="alert">
This is success
</div>

<br>

### Tab1
This is Tab 1

### Tab 2
This is Tab 2



## 第三段{#sec3}


<div id="pad">
```{r}
button_bs("See Collapse", class="info", data_toggle="collapse", aria_expanded="false", aria_controls="collapseExample", data_target = "#collapseExample")
```
</div>

```{r}
HTML('
<div class="collapse" id="collapseExample">
  <div class="alert alert-info">
    Collasped Text
  </div>
</div>')
```


<div class="panel panel-success">

<div class="panel-heading">
<h3 class="panel-title">Panel title</h3>
</div>

<div class="panel-body">
Panel content
</div>
  
</div>
<br><br><br><br><br><br><br><br><br>
